import { expect, test } from '@playwright/test'
test.use({ viewport: { width: 390, height: 844 } })
test('coach enters three games, corrects missed tackles, and reviews imported stats on a phone', async ({ page }) => {
  await page.goto('/#/game-stats')
  await expect(page.getByRole('heading', { name: 'Game Stats', exact: true })).toBeVisible()
  await page.getByLabel('Player', { exact: true }).selectOption({ index: 1 })
  await page.getByLabel('Show all offense and defense stats').check()
  for (const [i, date] of ['2026-09-01', '2026-09-08', '2026-09-15'].entries()) {
    await page.getByLabel('Game date', { exact: true }).fill(date)
    await page.getByLabel('Opponent', { exact: true }).fill(`Workflow Opponent ${i + 1}`)
    await page.getByLabel('Tackles', { exact: true }).fill('10')
    await page.getByLabel('Missed tackles', { exact: true }).fill('0')
    await page.getByRole('button', { name: 'Save game', exact: true }).click()
    await expect(page.getByText('Game saved. Rating updated.', { exact: false })).toBeVisible()
    if (i < 2) await page.getByRole('button', { name: 'Add another game' }).click()
  }
  await expect(page.getByText('3 saved games')).toBeVisible()
  await page.getByRole('button', { name: 'Edit Workflow Opponent 3 2026-09-15' }).click()
  await page.getByLabel('Missed tackles', { exact: true }).fill('30')
  await page.getByRole('button', { name: 'Save game', exact: true }).click()
  await expect(page.getByText('Game adjustment: -5%')).toBeVisible()
  await page.reload()
  await expect(page.getByText('3 saved games')).toBeVisible()
  await expect(page.getByText('Game adjustment: -5%')).toBeVisible()
  await page.getByRole('button', { name: 'Edit Workflow Opponent 3 2026-09-15' }).click()
  await expect(page.getByLabel('Missed tackles', { exact: true })).toHaveValue('30')
  await page.getByText('Upload Hudl stats or a screenshot', { exact: true }).click()
  await page.getByLabel('Paste stats or correct extracted text').fill('Tackles 12\nMissed tackles 0')
  await page.getByRole('button', { name: 'Review numbers', exact: true }).click()
  await page.getByRole('button', { name: 'Use reviewed numbers' }).click()
  await expect(page.getByLabel('Tackles', { exact: true })).toHaveValue('12')
  await page.getByRole('button', { name: 'Save game', exact: true }).click()
  await expect(page.getByText('Game adjustment: +5%')).toBeVisible()
  await expect(page.getByText('3 saved games')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.goto('/#/film')
  await expect(page).toHaveURL(/#\/game-stats/)
  await expect(page.getByRole('link', { name: 'Film Room', exact: true })).toHaveCount(0)
})

test('coach extracts a screenshot locally and reviews its numbers before saving', async ({ page, context }) => {
  test.setTimeout(120_000)
  const sheet = await context.newPage()
  await sheet.setViewportSize({ width: 900, height: 500 })
  await sheet.setContent('<main style="background:white;color:black;font:36px Arial;padding:32px;line-height:1.8">Tackles 12<br>Missed tackles 2<br>Sacks 1</main>')
  const screenshot = await sheet.screenshot()
  await sheet.close()
  await page.goto('/#/game-stats')
  await page.getByLabel('Player', { exact: true }).selectOption({ index: 1 })
  await page.getByText('Upload Hudl stats or a screenshot', { exact: true }).click()
  await page.getByLabel('Stat file or screenshot').setInputFiles({ name: 'game-stats.png', mimeType: 'image/png', buffer: screenshot })
  await expect(page.getByLabel('Paste stats or correct extracted text')).toHaveValue(/Tackles\s+12/, { timeout: 90_000 })
  await page.getByRole('button', { name: 'Review numbers', exact: true }).click()
  await page.getByRole('button', { name: 'Use reviewed numbers' }).click()
  await expect(page.getByLabel('Tackles', { exact: true })).toHaveValue('12')
  await expect(page.getByLabel('Missed tackles', { exact: true })).toHaveValue('2')
  await expect(page.getByText('No games saved yet.')).toBeVisible()
})
