import { expect, test } from '@playwright/test'
test.use({ viewport: { width: 390, height: 844 } })
test('coach grades, reloads, and downloads a weekly packet on a phone', async ({ page }) => {
  await page.goto('/reports')
  await expect(page.getByRole('heading', { name: 'Weekly Reports', exact: true })).toBeVisible()
  await expect(page.getByText('Loading saved evaluations…')).not.toBeVisible()
  await page.getByLabel('Game date', { exact: true }).fill('2026-09-14')
  await page.getByLabel('Opponent', { exact: true }).fill('Report Test Opponent')
  await page.getByLabel('Position group', { exact: true }).selectOption('RB')
  await expect(page.getByLabel('Athlete', { exact: true }).locator('option')).not.toHaveCount(1)
  await page.getByLabel('Athlete', { exact: true }).selectOption({ index: 1 })
  await page.getByRole('button', { name: 'Open evaluation', exact: true }).click()
  await page.getByLabel('Grading coach', { exact: true }).fill('Coach Test')
  await page.getByLabel('Score for criterion 1', { exact: true }).selectOption('2')
  await page.getByLabel('Score for criterion 2', { exact: true }).selectOption('0')
  await page.getByLabel('Player feedback', { exact: true }).fill('Keep shoulders square.')
  await page.getByLabel('Next practice focus', { exact: true }).fill('Three pass protection reps.')
  await page.getByRole('button', { name: 'Save evaluation', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('Evaluation saved.')
  await page.reload()
  await expect(page.getByText('Loading saved evaluations…')).not.toBeVisible()
  await page.getByLabel('Saved games', { exact: true }).selectOption({ index: 1 })
  await expect(page.getByText('50%', { exact: true })).toBeVisible()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download printable packet', exact: true }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('fai-weekly-report-2026-09-14.html')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
